name: CDIS
channels:
  - conda-forge
#  - brown-data-science # (pdf2svg)
dependencies:
  - python=3.7
  - pip
  - pandoc=2.8.1
  - numpy
  - scipy
  - mpmath
  - autograd
  - matplotlib
  - black
#  - librsvg # Linux or OSX only ...
#  - predictmd-pdf2svg # Linux only ...
  - pip:
    - ics==0.4
    - "-e git+https://github.com/boisgera/pandoc@3e16b7046fcc7ce1610b041d3b5add15e4df12ac#egg=pandoc"
